import { Link } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-r from-zinc-900 via-stone-950 to-stone-900 flex items-center justify-center p-4">
      <div className="relative w-full max-w-3xl">
        <Link href="/signup">
          <Button variant="ghost" className="absolute left-0 z-[100] text-white/70 hover:text-white hover:scale-110 transition-all">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Signup
          </Button>
        </Link>
        <Card className="bg-white/10 backdrop-blur-lg border border-white/20 shadow-2xl text-white">
          <CardHeader>
          <CardTitle className="text-2xl pt-10px">Terms of Use / Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-invert max-w-none space-y-4">
          <p>
          These Terms of Use (“Terms”) govern the use of ProfessorsAI (“Platform”), an artificial 
          intelligence–powered teaching, mentoring, and examination system provided by 
          [Your Company Name] (“We,” “Us,” “Our”). By accessing or using the Platform, you 
          (“the User”) agree to these Terms. Please read them carefully before engaging 
          with ProfessorsAI.
          </p>

          <h3>1. Purpose of the Platform</h3>
          <p>
          ProfessorsAI is an educational technology solution designed to deliver interactive 
          teaching, provide mentoring and academic guidance, and conduct practice examinations 
          and assessments. The Platform is an AI-based system and is not a substitute for human 
          teachers, university faculty, or statutory examination boards. While we strive to ensure 
          accuracy, ProfessorsAI may generate content that is incomplete, outdated, or incorrect. 
          Users must exercise discretion and verify any academic advice, results, or outputs with 
          qualified professionals or recognized institutions.
          </p>

          <h3>2. Disclaimer of Liability</h3>
          <p>
          We do not guarantee the accuracy, completeness, reliability, or fitness of the Platform 
          for a specific purpose, and the Platform is provided on an “as is” and “as available” 
          basis. To the extent permitted under Indian law, we disclaim all liability for direct, 
          indirect, incidental, or consequential damages arising from the use of ProfessorsAI. 
          Our maximum liability, if established by a competent court, shall not exceed the 
          subscription fees (if any) paid by the User in the preceding six months.
          </p>

          <h3>3. Governing Law and Jurisdiction</h3>
          <p>
          These Terms are governed by and construed in accordance with the laws of India, and the 
          courts of [Jurisdiction, Noida] shall have exclusive jurisdiction over any dispute. The 
          Platform complies with applicable provisions of the Information Technology Act, 2000 
          and the Digital Personal Data Protection Act, 2023 (DPDP Act).
          </p>

          <h3>4. User Eligibility</h3>
          <p>
          Users must be at least eighteen years of age, or the age of majority in their jurisdiction, 
          to use the Platform independently. Users under eighteen may use ProfessorsAI only under 
          the supervision of a parent, guardian, or authorized institution.
          </p>

          <h3>5. Prohibited Activities</h3>
          <p>
          By using ProfessorsAI, Users agree not to post or transmit unlawful, defamatory, obscene, 
          offensive, discriminatory, or harmful content; not to use the Platform for cheating, 
          impersonation, or activities that violate academic integrity; not to attempt to hack, 
          disrupt, or gain unauthorized access; and not to reverse engineer, copy, or commercially 
          exploit the Platform without prior written consent.
          </p>

          <h3>6. Academic Integrity</h3>
          <p>
          ProfessorsAI is intended only as a supplementary tool for learning, mentoring, and practice 
          examinations. It does not replace accredited teachers, universities, or statutory 
          examination authorities in India. Marks, scores, or assessments generated by ProfessorsAI 
          are indicative only and not legally binding, with recognized institutions retaining full 
          authority for curriculum design, grading, and certification.
          </p>

          <h3>7. Data Protection and Privacy</h3>
          <p>
          We comply with the Digital Personal Data Protection Act, 2023 and other applicable rules, 
          and user personal data will only be collected, processed, and stored for legitimate 
          educational purposes with appropriate consent. Some conversations may be reviewed to 
          improve system performance, quality, and safety. Users are advised not to share unnecessary 
          sensitive personal data, such as Aadhaar numbers, financial details, or health data, unless 
          explicitly required, and we will not share data with third parties without consent, except 
          as mandated under Indian law or by government authorities.
          </p>

          <h3>8. Suspension or Termination</h3>
          <p>
          We reserve the right to suspend or terminate access to ProfessorsAI without notice if a 
          User violates these Terms, engages in prohibited conduct, or if required by applicable 
          law or educational policy.
          </p>

          <h3>9. Acknowledgement</h3>
          <p>
          By using ProfessorsAI, you acknowledge that you have read, understood, and agreed to these 
          Terms of Use and Disclaimer. If you do not agree, please refrain from using the Platform. 
          For assistance or legal queries, you may contact [Insert official support email/website].
          </p>

          <p className="text-sm text-white/70">
          This Terms of Use and Disclaimer is provided for legal and educational clarity under Indian law.
          </p>
          </CardContent>
          </Card>

      </div>
    </div>
  );
}
