import pg from 'pg';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '..', '.env') });

const { Client } = pg;

async function backupDatabase() {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const backupDir = path.join(__dirname, '..', 'database-backups');
  const backupFile = path.join(backupDir, `prof_AI_backup_${timestamp}.sql`);

  if (!fs.existsSync(backupDir)) {
    fs.mkdirSync(backupDir, { recursive: true });
    console.log(`Created backup directory: ${backupDir}`);
  }

  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    console.log('Connecting to database...');
    await client.connect();
    console.log('Connected successfully!\n');

    console.log('Starting database backup...');
    console.log(`Backup file: ${backupFile}\n`);

    let sqlDump = `-- PostgreSQL Database Backup
-- Database: prof_AI
-- Timestamp: ${new Date().toISOString()}
-- Generated by ProfAICoach Backup Script

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

`;

    // Get all tables
    const tablesResult = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `);

    console.log(`Found ${tablesResult.rows.length} tables to backup:\n`);

    for (const { table_name } of tablesResult.rows) {
      console.log(`Backing up table: ${table_name}...`);

      // Get table schema
      const schemaResult = await client.query(`
        SELECT column_name, data_type, character_maximum_length, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY ordinal_position;
      `, [table_name]);

      sqlDump += `\n-- Table: ${table_name}\n`;
      sqlDump += `DROP TABLE IF EXISTS "${table_name}" CASCADE;\n`;
      
      // Create table statement
      sqlDump += `CREATE TABLE "${table_name}" (\n`;
      const columns = schemaResult.rows.map((col, idx) => {
        let colDef = `  "${col.column_name}" ${col.data_type}`;
        if (col.character_maximum_length) {
          colDef += `(${col.character_maximum_length})`;
        }
        if (col.is_nullable === 'NO') {
          colDef += ' NOT NULL';
        }
        if (col.column_default) {
          colDef += ` DEFAULT ${col.column_default}`;
        }
        return colDef;
      });
      sqlDump += columns.join(',\n');
      sqlDump += '\n);\n\n';

      // Get table data
      const dataResult = await client.query(`SELECT * FROM "${table_name}"`);
      
      if (dataResult.rows.length > 0) {
        console.log(`  - ${dataResult.rows.length} rows`);
        
        for (const row of dataResult.rows) {
          const columnNames = Object.keys(row).map(k => `"${k}"`).join(', ');
          const values = Object.values(row).map(v => {
            if (v === null) return 'NULL';
            if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`;
            if (typeof v === 'boolean') return v ? 'true' : 'false';
            if (v instanceof Date) return `'${v.toISOString()}'`;
            if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
            return v;
          }).join(', ');
          
          sqlDump += `INSERT INTO "${table_name}" (${columnNames}) VALUES (${values});\n`;
        }
        sqlDump += '\n';
      } else {
        console.log(`  - 0 rows (empty table)`);
      }
    }

    // Get sequences
    const sequencesResult = await client.query(`
      SELECT sequence_name 
      FROM information_schema.sequences 
      WHERE sequence_schema = 'public';
    `);

    if (sequencesResult.rows.length > 0) {
      sqlDump += '\n-- Sequences\n';
      for (const { sequence_name } of sequencesResult.rows) {
        const seqResult = await client.query(`SELECT last_value FROM "${sequence_name}"`);
        if (seqResult.rows.length > 0) {
          sqlDump += `SELECT setval('${sequence_name}', ${seqResult.rows[0].last_value}, true);\n`;
        }
      }
    }

    // Write to file
    fs.writeFileSync(backupFile, sqlDump, 'utf8');

    const stats = fs.statSync(backupFile);
    const fileSizeMB = (stats.size / (1024 * 1024)).toFixed(2);

    console.log('\n✓ Backup completed successfully!');
    console.log(`File: ${backupFile}`);
    console.log(`Size: ${fileSizeMB} MB`);

  } catch (error) {
    console.error('\n✗ Backup failed!');
    console.error('Error:', error);
    process.exit(1);
  } finally {
    await client.end();
  }
}

backupDatabase();
